SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (1, N'Nike Air Max 90 Recraft', CAST(11490 AS Decimal(18, 0)), N'Red', N'Male', N'The best snickers', 15, N'Sneakers', 41, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (2, N'Jack & Jones Essentials', CAST(1090 AS Decimal(18, 0)), N'White', N'Male', N'White long oval neckline t-shirt', 10, N'T-shirt', 48, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (3, N'ASOS DESIGN Tall', CAST(1090 AS Decimal(18, 0)), N'Green', N'Male', N'Green Organic Cotton T-shirt with Contrast Ribbon

', 5, N'T-shirt', 48, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (5, N'Tommy Hilfiger - authentic', CAST(2970 AS Decimal(18, 0)), N'Gray', N'Male', N'Gray home T-shirt with signature ribbon on the sides', 10, N'T-shirt', 50, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (6, N'Religion', CAST(2790 AS Decimal(18, 0)), N'White', N'Male', N'White Skeleton T-shirt', 13, N'T-shirt', 45, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (7, N'ASOS DESIGN Lavender', CAST(1890 AS Decimal(18, 0)), N'Pink', N'Male', N'Photo print oversized t-shirt', 17, N'T-shirt', 42, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (8, N'Palladium Boots', CAST(5990 AS Decimal(18, 0)), N'Black', N'Male', N'Black high boots', 20, N'Boots', 43, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (9, N'Bershka Trousers', CAST(2799 AS Decimal(18, 0)), N'Gray', N'Male', N'Gray Corduroy Skinny Pants', 25, N'Trousers', 45, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (11, N'boohooMAN', CAST(2180 AS Decimal(18, 0)), N'Gray', N'Male', N'Gray Cropped Striped Pants', 30, N'Trousers', 42, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (12, N'ASOS DESIGN chinos', CAST(1790 AS Decimal(18, 0)), N'Gray', N'Male', N'Blue Super Slim Chinos with Elastic Waist', 15, N'Trousers', 45, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (13, N'Vans Authentic', CAST(3490 AS Decimal(18, 0)), N'Pink', N'Female', N'Pink sneakers with white accents', 10, N'Sneakers', 38, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (14, N'Fila orbit zeppa', CAST(3890 AS Decimal(18, 0)), N'Cream', N'Female', N'Sneakers Fila orbit zeppa', 15, N'Sneakers', 35, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (15, N'Ray-Ban Glasses', CAST(5190 AS Decimal(18, 0)), N'Tortoiseshell', N'Female', N'Clear Glasses', 5, N'Glasses', 0, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (16, N'Consigned', CAST(2190 AS Decimal(18, 0)), N'Pink', N'Female', N'Backpack with zipper', 10, N'Backpack ', 0, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (17, N'ASOS DESIGN Curve', CAST(2890 AS Decimal(18, 0)), N'Pink', N'Female', N'Sweatshirt and color block joggers tracksuit', 15, N'Sweatshirt ', 54, NULL)
INSERT INTO [dbo].[Product] ([Id], [NameProduct], [Price], [Color], [Gender], [Description], [QuantityOfGoods], [Category], [Size], [ImageProduct]) VALUES (18, N'ASOS DESIGN Petite', CAST(1890 AS Decimal(18, 0)), N'Black', N'Female', N'Flax mix cigarette pants', 10, N'Trousers', 36, NULL)
SET IDENTITY_INSERT [dbo].[Product] OFF
